apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  authorization_token: {{ required .Values.slackConfiguration.authorization_token | b64enc }}
  db_connection: {{ required Values.slackConfiguration.db_connection | b64enc }}