# Namespace
namespace: slack

# Number of Replicas to Create
replicaCount: 1

# Image Properties
image:
  repository: morehumansoftware/slack-user-scraper
  tag: latest
  pullPolicy: Always

# Default Service Specification
service:
  name: slack-user-scraper-metrics
  type: ClusterIP
  internalPort: 3001
  externalPort: 3001

# Default Resource Quotas
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Ingress
ingress:
  enabled: false

# Slack Configuration
slackConfiguration:
  slackUrl: slack.com